# extension.toml
# See: https://crates.io/crates/zed_extension_api
id = "playdate"
name = "Playdate"
schema_version = 1
version = "0.1.1"
authors = ["Peter Tripp <petertripp@gmail.com>"]
description = "Playdate support for Zed."
repository = "https://github.com/notpeter/playdate-zed-extension"

[grammars.pdxinfo]
repository = "https://github.com/notpeter/tree-sitter-pdxinfo"
commit = "f53aa27c0f93c0b89367894c8858528cf0b85e81"

[grammars.animationtxt]
repository = "https://github.com/notpeter/tree-sitter-animationtxt"
commit = "d7947cdcc94fbad7a2436053572552adf471fc9b"
